name: Build and Release Obsidian Plugin

on:
  push:
    branches:
      - master  # Запуск при пуше в master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build plugin
        run: npm run build

      - name: Create release ZIP
        run: |
          mkdir release
          cp main.js manifest.json styles.css release/
          cd release
          zip -r obsidian-plugin.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: obsidian-plugin
          path: release/obsidian-plugin.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: obsidian-plugin
          path: release

      - name: Get version from manifest.json
        id: get_version
        run: echo "VERSION=$(jq -r .version manifest.json)" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: release/obsidian-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
