name: Notify Telegram on Issues and Pull Requests

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened, review_requested, ready_for_review, synchronize]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Create message file
        run: |
          TITLE="${{ github.event.issue.title || github.event.pull_request.title || 'Комментарий' }}"
          COMMENT="${{ github.event.comment.body || '' }}"
          MSG="Repository: ${{ github.repository }}
Type: ${{ github.event_name }}
Action: ${{ github.event.action }}
Title: ${TITLE}
${COMMENT}

See: ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url || github.event.review.html_url }}"
          echo "$MSG" > message.txt
          LENGTH=$(wc -c < message.txt)
          echo "MESSAGE_LENGTH=$LENGTH" >> $GITHUB_ENV

      - name: Send full message if short
        if: ${{ env.MESSAGE_LENGTH < 4096 }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_file: message.txt

      - name: Send only link if message too long
        if: ${{ env.MESSAGE_LENGTH >= 4096 }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            See: ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url || github.event.review.html_url }}
