name: Notify Telegram on Issues and Pull Requests

on:
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened, review_requested, ready_for_review, synchronize]
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Telegram message
        id: prepare_message
        run: |
          FULL_MESSAGE="Repository: ${{ github.repository }}\nType: ${{ github.event_name }}\nAction: ${{ github.event.action }}\nTitle: ${{ github.event.issue.title || github.event.pull_request.title || 'Комментарий' }}\n${{ github.event.comment.body || '' }}\nSee ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url || github.event.review.html_url }}"
          SHORT_MESSAGE="Repository: ${{ github.repository }}\nUpdate in ${{ github.event_name }} (${{ github.event.action }})\nTitle: ${{ github.event.issue.title || github.event.pull_request.title || 'Комментарий' }}\nSee ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.comment.html_url || github.event.review.html_url }}"
          
          # Проверяем длину сообщения (лимит Telegram — 4096 символов)
          if [ ${#FULL_MESSAGE} -gt 4096 ]; then
            echo "message=$SHORT_MESSAGE" >> $GITHUB_OUTPUT
          else
            echo "message=$FULL_MESSAGE" >> $GITHUB_OUTPUT
          fi

      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ steps.prepare_message.outputs.message }}
